# @format

name: direct2u
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_fadein: 2.0.0
  velocity_x: 3.5.1
  retrofit: ^3.0.1
  get_storage: ^2.0.3
  faker: 2.0.0
  flutter_image_slideshow: 0.1.2
  persistent_bottom_nav_bar: 4.0.2
  intl: 0.17.0
  lottie: ^1.4.0
  file_picker: ^5.0.0
  image_picker: ^0.8.5+3
  razorpay_flutter: ^1.3.0
  rating_dialog: ^2.0.4
  firebase_dynamic_links: ^4.3.3
  firebase_core: ^1.20.0
  share_plus: ^4.0.10
  flutter_facebook_auth: ^4.4.0+1
  stream_transform: 2.0.0
  speech_to_text: ^5.6.0
  badges: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_gen_runner: any
  retrofit_generator: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
